USE universe_scout;

UPDATE team SET team_name_cn = '76人' WHERE team_name_en = '76ers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '雄鹿' WHERE team_name_en = 'Bucks' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '公牛' WHERE team_name_en = 'Bulls' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '骑士' WHERE team_name_en = 'Cavaliers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '凯尔特人' WHERE team_name_en = 'Celtics' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '快船' WHERE team_name_en = 'Clippers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '灰熊' WHERE team_name_en = 'Grizzlies' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '老鹰' WHERE team_name_en = 'Hawks' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '热火' WHERE team_name_en = 'Heat' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '黄蜂' WHERE team_name_en = 'Hornets' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '爵士' WHERE team_name_en = 'Jazz' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '国王' WHERE team_name_en = 'Kings' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '尼克斯' WHERE team_name_en = 'Knicks' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '湖人' WHERE team_name_en = 'Lakers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '魔术' WHERE team_name_en = 'Magic' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '独行侠' WHERE team_name_en = 'Mavericks' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '篮网' WHERE team_name_en = 'Nets' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '掘金' WHERE team_name_en = 'Nuggets' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '步行者' WHERE team_name_en = 'Pacers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '鹈鹕' WHERE team_name_en = 'Pelicans' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '活塞' WHERE team_name_en = 'Pistons' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '猛龙' WHERE team_name_en = 'Raptors' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '火箭' WHERE team_name_en = 'Rockets' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '马刺' WHERE team_name_en = 'Spurs' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '太阳' WHERE team_name_en = 'Suns' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '雷霆' WHERE team_name_en = 'Thunder' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '森林狼' WHERE team_name_en = 'Timberwolves' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '开拓者' WHERE team_name_en = 'Trail Blazers' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '勇士' WHERE team_name_en = 'Warriors' AND (team_name_cn IS NULL OR team_name_cn = '');
UPDATE team SET team_name_cn = '奇才' WHERE team_name_en = 'Wizards' AND (team_name_cn IS NULL OR team_name_cn = '');
